- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.inputrc:
    ~/.pythonrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.jupyter:
    ~/.zsh:
    ~/.zshrc:
    ~/.config/starship.toml:
    ~/.config/nvim: nvim

    # macOS only (will be dangling symlinks on Linux, but harmless)
    ~/.hammerspoon:

- create:
  - ~/.hammerspoon

- shell:
  - git submodule sync --recursive
  - git update-submodules
  - >
    git cleanall -f
    zsh/plugins/
